# Generated by Django 5.1.4 on 2025-09-28 17:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Mi Empresa', max_length=100)),
                ('moneda', models.CharField(default='MXN', max_length=5)),
                ('stock_minimo_alerta', models.PositiveIntegerField(default=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: M001', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Ej: Listón rojo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle del material')),
                ('tipo_material', models.CharField(choices=[('paquete', 'Paquete'), ('rollo', 'Rollo')], max_length=10)),
                ('unidad_base', models.CharField(choices=[('unidades', 'Unidades'), ('cm', 'Centímetros')], max_length=10)),
                ('factor_conversion', models.PositiveIntegerField(help_text='Cantidad que representa 1 paquete o 1 rollo en unidad base')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, help_text='Stock actual en unidad base', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio total de la compra', max_digits=10)),
                ('categoria', models.CharField(help_text='Ej: listón, piedra, adorno', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Monos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: MO001', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Ej: Moño básico', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle del moño')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta por unidad o par', max_digits=10)),
                ('tipo_venta', models.CharField(choices=[('individual', 'Individual'), ('par', 'Par')], default='individual', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moño',
                'verbose_name_plural': 'Moños',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada/Reabastecimiento'), ('salida', 'Salida Normal'), ('produccion', 'Salida por Producción'), ('ajuste', 'Ajuste de Inventario')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad afectada en unidad base (positiva para entrada, negativa para salida)', max_digits=10)),
                ('cantidad_anterior', models.DecimalField(decimal_places=2, help_text='Cantidad antes del movimiento', max_digits=10)),
                ('cantidad_nueva', models.DecimalField(decimal_places=2, help_text='Cantidad después del movimiento', max_digits=10)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario al momento del movimiento', max_digits=10, null=True)),
                ('costo_total_movimiento', models.DecimalField(blank=True, decimal_places=2, help_text='Costo total del movimiento', max_digits=10, null=True)),
                ('detalle', models.TextField(help_text='Motivo del movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.material')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producir', models.PositiveIntegerField(help_text='Cantidad de moños a producir')),
                ('tipo_venta', models.CharField(choices=[('individual', 'Individual'), ('par', 'Par')], max_length=10)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, help_text='Precio de venta por unidad o par', max_digits=10)),
                ('cantidad_total_monos', models.PositiveIntegerField(help_text='Cantidad total considerando tipo de venta')),
                ('costo_total_produccion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingreso_total_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ganancia_estimada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('necesita_compras', models.BooleanField(default=False)),
                ('costo_total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to='inventario.monos')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulación',
                'verbose_name_plural': 'Simulaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.CharField(help_text='Descripción del movimiento', max_length=200)),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('categoria', models.CharField(choices=[('venta', 'Venta de Productos'), ('inventario', 'Compra de Inventario'), ('produccion', 'Costo de Producción'), ('sueldo', 'Sueldos'), ('renta', 'Renta'), ('servicio', 'Servicios (luz, agua, etc.)'), ('otro_gasto', 'Otros Gastos'), ('otro_ingreso', 'Otros Ingresos')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del movimiento (siempre positivo)', max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, help_text='Saldo antes del movimiento', max_digits=12)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, help_text='Saldo después del movimiento', max_digits=12)),
                ('automatico', models.BooleanField(default=False, help_text='True si fue generado automáticamente por el sistema')),
                ('movimiento_inventario', models.ForeignKey(blank=True, help_text='Movimiento de inventario relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimiento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('simulacion_relacionada', models.ForeignKey(blank=True, help_text='Simulación relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.simulacion')),
            ],
            options={
                'verbose_name': 'Movimiento de Efectivo',
                'verbose_name_plural': 'Movimientos de Efectivo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='simulacion_relacionada',
            field=models.ForeignKey(blank=True, help_text='Simulación relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.simulacion'),
        ),
        migrations.CreateModel(
            name='DetalleSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_faltante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_a_comprar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidades_completas_comprar', models.PositiveIntegerField(default=0)),
                ('costo_compra_necesaria', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suficiente_stock', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material')),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.simulacion')),
            ],
            options={
                'verbose_name': 'Detalle de Simulación',
                'verbose_name_plural': 'Detalles de Simulaciones',
            },
        ),
        migrations.CreateModel(
            name='RecetaMonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, help_text='Cantidad de material necesaria por moño en unidad base', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material')),
                ('monos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='inventario.monos')),
            ],
            options={
                'verbose_name': 'Receta de Moño',
                'verbose_name_plural': 'Recetas de Moños',
                'ordering': ['material__nombre'],
                'unique_together': {('monos', 'material')},
            },
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['material', 'fecha'], name='inventario__materia_3f4130_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo_movimiento', 'fecha'], name='inventario__tipo_mo_96e909_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['usuario', 'fecha'], name='inventario__usuario_244009_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesimulacion',
            unique_together={('simulacion', 'material')},
        ),
    ]
