# Generated by Django 5.1.4 on 2025-09-27 15:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador único (ej. M001)', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del material (ej. Listón rojo)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle del material')),
                ('tipo_material', models.CharField(choices=[('paquete', 'Paquete'), ('rollo', 'Rollo')], max_length=10)),
                ('unidad_base', models.CharField(choices=[('unidades', 'Unidades'), ('cm', 'Centímetros')], max_length=10)),
                ('factor_conversion', models.PositiveIntegerField(help_text='Cantidad que representa 1 paquete o 1 rollo en unidad base')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, help_text='Stock actual en unidad base')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio total de la compra (reabastecer)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Precio por unidad base (precio_compra / factor_conversion)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('categoria', models.CharField(help_text='Clasificación (ej. listón, piedra, adorno)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del insumo (ej. Moño básico)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle del insumo')),
                ('cantidad_por_unidad', models.PositiveIntegerField(help_text='Cantidad de material que se usa por cada moño')),
                ('unidad_consumo', models.CharField(choices=[('unidades', 'Unidades'), ('cm', 'Centímetros')], help_text='Unidad en la que se descuenta (unidades | cm)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(help_text='Material al que está vinculado', on_delete=django.db.models.deletion.CASCADE, to='inventario.material')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField(help_text='Cantidad afectada en unidad base (puede ser negativa)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(help_text='Motivo (ej. "Compra proveedor X", "Producción de 50 moños")')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
