# Generated by Django 5.1.4 on 2025-09-27 20:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reabastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(help_text='Cantidad a solicitar en unidad base')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, help_text='Cantidad realmente recibida')),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor o lugar de compra', max_length=100)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio estimado total de la compra', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('precio_real', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio real pagado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('solicitado', 'Solicitado'), ('en_transito', 'En Tránsito'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_llegada', models.DateTimeField(blank=True, help_text='Fecha estimada de llegada del pedido', null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, help_text='Fecha real cuando se recibió el pedido', null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales del reabastecimiento')),
                ('stock_minimo_sugerido', models.PositiveIntegerField(blank=True, help_text='Nivel mínimo de stock sugerido para este material', null=True)),
                ('automatico', models.BooleanField(default=False, help_text='Si fue generado automáticamente por stock bajo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(help_text='Material a reabastecer', on_delete=django.db.models.deletion.CASCADE, to='inventario.material')),
            ],
            options={
                'verbose_name': 'Reabastecimiento',
                'verbose_name_plural': 'Reabastecimientos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
