# Generated by Django 5.1.4 on 2025-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='factor_conversion',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad que representa 1 paquete o 1 rollo en unidad base'),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio total de la compra', max_digits=10),
        ),
    ]
