# Generated by Django 5.1.4 on 2025-09-28 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_material_factor_conversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la lista de producción', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la lista')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_compra', 'Pendiente de Compra'), ('comprado', 'Materiales Comprados'), ('reabastecido', 'Inventario Reabastecido'), ('en_produccion', 'En Producción'), ('finalizado', 'Finalizado')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('total_moños_planificados', models.PositiveIntegerField(default=0)),
                ('total_moños_producidos', models.PositiveIntegerField(default=0)),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Producción',
                'verbose_name_plural': 'Listas de Producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleListaMonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pares', models.PositiveIntegerField(default=0, help_text='Cantidad de pares a producir')),
                ('cantidad_individuales', models.PositiveIntegerField(default=0, help_text='Cantidad de moños individuales a producir')),
                ('pares_producidos', models.PositiveIntegerField(default=0)),
                ('individuales_producidos', models.PositiveIntegerField(default=0)),
                ('monos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_lista', to='inventario.monos')),
                ('lista_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_monos', to='inventario.listaproduccion')),
            ],
            options={
                'verbose_name': 'Detalle de Moños en Lista',
                'verbose_name_plural': 'Detalles de Moños en Listas',
                'unique_together': {('lista_produccion', 'monos')},
            },
        ),
        migrations.CreateModel(
            name='ResumenMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad total necesaria para la producción', max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad disponible al momento de crear la lista', max_digits=10)),
                ('cantidad_faltante', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad que falta comprar', max_digits=10)),
                ('cantidad_comprada', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad realmente comprada', max_digits=10)),
                ('precio_compra_real', models.DecimalField(decimal_places=2, default=0, help_text='Precio real pagado por el material', max_digits=10)),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad realmente utilizada en la producción', max_digits=10)),
                ('lista_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_materiales', to='inventario.listaproduccion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_lista', to='inventario.material')),
            ],
            options={
                'verbose_name': 'Resumen de Material',
                'verbose_name_plural': 'Resumen de Materiales',
                'unique_together': {('lista_produccion', 'material')},
            },
        ),
    ]
