# Generated by Django 5.1.4 on 2025-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_add_lista_produccion_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallelistamonos',
            old_name='individuales_producidos',
            new_name='cantidad_producida',
        ),
        migrations.RemoveField(
            model_name='detallelistamonos',
            name='cantidad_individuales',
        ),
        migrations.RemoveField(
            model_name='detallelistamonos',
            name='cantidad_pares',
        ),
        migrations.RemoveField(
            model_name='detallelistamonos',
            name='pares_producidos',
        ),
        migrations.AddField(
            model_name='detallelistamonos',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad a producir (pares o individuales según el tipo del moño)'),
        ),
    ]
