# Generated by Django 5.1.4 on 2025-09-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_individuales_producidos_detallelistamonos_cantidad_producida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenmateriales',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se realizó la compra', null=True),
        ),
        migrations.AddField(
            model_name='resumenmateriales',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Proveedor donde se compró el material', max_length=200),
        ),
    ]
