# Generated by Django 5.1.4 on 2025-09-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_resumenmateriales_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaproduccion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_compra', 'Pendiente de Compra'), ('comprado', 'Materiales Comprados'), ('reabastecido', 'Inventario Reabastecido'), ('en_produccion', 'En Producción'), ('en_salida', 'Lista en Salida'), ('finalizado', 'Finalizado')], default='borrador', max_length=20),
        ),
    ]
