# Generated by Django 5.1.4 on 2025-10-05 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_add_archivado_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaMonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.PositiveIntegerField(help_text='Cantidad vendida (pares o individuales según tipo_venta)')),
                ('tipo_venta', models.CharField(choices=[('individual', 'Individual'), ('par', 'Par')], help_text='Tipo de venta: individual o par', max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio de venta por unidad/par', max_digits=10)),
                ('ingreso_total', models.DecimalField(decimal_places=2, help_text='Ingreso total de esta venta', max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Costo de producción por unidad/par', max_digits=10)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0, help_text='Ganancia de esta venta', max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lista_produccion', models.ForeignKey(blank=True, help_text='Lista de producción relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_monos', to='inventario.listaproduccion')),
                ('monos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='inventario.monos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta de Moño',
                'verbose_name_plural': 'Ventas de Moños',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['monos', 'fecha'], name='inventario__monos_i_3f1586_idx'), models.Index(fields=['fecha'], name='inventario__fecha_5e1463_idx')],
            },
        ),
    ]
